export const INTEREST_POOL = [
  "music",
  "art",
  "photography",
  "painting",
  "sculpture",
  "theatre",
  "cinema",
  "dance",
  "literature",
  "poetry",
  "dj-ing",
  "stand-up comedy",
  "acting",
  "football",
  "basketball",
  "cricket",
  "tennis",
  "badminton",
  "running",
  "cycling",
  "swimming",
  "yoga",
  "pilates",
  "climbing",
  "martial arts",
  "surfing",
  "skiing",
  "snowboarding",
  "coding",
  "robotics",
  "AI",
  "blockchain",
  "cybersecurity",
  "electronics",
  "engineering",
  "3D printing",
  "space exploration",
  "gaming",
  "board games",
  "e-sports",
  "VR",
  "anime",
  "manga",
  "podcasting",
  "blogging",
  "vlogging",
  "travel",
  "backpacking",
  "camping",
  "hiking",
  "bird-watching",
  "astronomy",
  "gardening",
  "beekeeping",
  "sailing",
  "fishing",
  "cooking",
  "baking",
  "mixology",
  "coffee culture",
  "wine tasting",
  "beer brewing",
  "vegan cuisine",
  "woodworking",
  "knitting",
  "crocheting",
  "origami",
  "calligraphy",
  "leathercraft",
  "pottery",
  "jewelry making",
  "scrapbooking",
  "meditation",
  "mindfulness",
  "journaling",
  "astrology",
  "tarot",
  "self-help",
  "volunteering",
  "activism",
  "sustainability",
  "minimalism",
  "environmentalism",
  "animal welfare",
  "philosophy",
  "investing",
  "crypto",
  "entrepreneurship",
  "economics",
] as const;

export const TEST_SEEDS = [
  { lon: 82.75, lat: 22.5 },
  { lon: 68.0, lat: 8.0 },
  { lon: 97.5, lat: 8.0 },
  { lon: 68.0, lat: 37.0 },
  { lon: 97.5, lat: 37.0 },
  { lon: 77.1025, lat: 28.7041 },
  { lon: 72.8777, lat: 19.076 },
  { lon: 77.5946, lat: 12.9716 },
  { lon: 88.3639, lat: 22.5726 },
  { lon: 80.2707, lat: 13.0827 },
];
